CiscoSystems\ActivityBundle\Entity\Activity:
    type: entity
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    table: cisco_activity__activity
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        user:
            targetEntity: CiscoSystems\ActivityBundle\Model\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
        parent:
            targetEntity: CiscoSystems\ActivityBundle\Entity\Activity
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: SET NULL
            gedmo:
                - treeParent
        project:
            targetEntity: CiscoSystems\ActivityBundle\Entity\Project
            inversedBy: activities
            joinColumn:
                name: project_id
                referencedColumnName: id
    oneToMany:
        children:
            targetEntity: CiscoSystems\ActivityBundle\Entity\Activity
            mappedBy: parent
            orderBy:
                lft: ASC
    fields:
        title:
            type: string
            length: 128
        description:
            type: text
            nullable: true
        timeEstimated:
            column: time_estimated
            type: integer
            nullable: true
        timeSpent:
            column: time_spent
            type: integer
            nullable: true
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields:
                        - title
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        completedAt:
            column: completed_at
            type: datetime
            nullable: true
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel