WG\ActivityBundle\Entity\Milestone:
    type: entity
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    table: wg_activity__milestone
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        parent:
            targetEntity: WG\ActivityBundle\Entity\Milestone
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: SET NULL
            gedmo:
                - treeParent
        project:
            targetEntity: WG\ActivityBundle\Entity\Project
            inversedBy: milestones
            joinColumn:
                name: project_id
                referencedColumnName: id
    oneToMany:
        children:
            targetEntity: WG\ActivityBundle\Entity\Milestone
            mappedBy: parent
            orderBy:
                lft: ASC
    fields:
        dueBy:
            column: due_by
            type: datetime
        title:
            type: string
            length: 128
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields:
                        - title
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel