CiscoSystems\ActivityBundle\Entity\WorkUnit:
    type: entity
    table: cisco_activity__workunit
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToOne:
        user:
            targetEntity: CiscoSystems\ActivityBundle\Model\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
        activity:
            targetEntity: CiscoSystems\ActivityBundle\Entity\Activity
            joinColumn:
                name: activity_id
                referencedColumnName: id
    fields:
        timeSpent:
            column: time_spent
            type: integer
        tracking:
            type: boolean
        startedAt:
            column: started_at
            type: datetime
        stoppedAt:
            column: stopped_at
            type: datetime