CiscoSystems\ActivityBundle\Entity\WorkWeek:
    type: entity
    table: cisco_activity__workweek
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToOne:
        user:
            targetEntity: CiscoSystems\ActivityBundle\Model\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
    fields:
        hours:
            type: integer
        days:
            type: integer