services:
    cisco.activity.activity.form:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - cisco_activity_activity
            - '@cisco.activity.activity.form.type'
    cisco.activity.activity.form.type:
        class:  CiscoSystems\ActivityBundle\Form\Type\ActivityFormType
        arguments:
            - CiscoSystems\ActivityBundle\Entity\Activity
    cisco.activity.activity.form.handler:
        class: CiscoSystems\ActivityBundle\Form\FormHandler
        arguments:
            - '@cisco.activity.activity.form'
            - '@request'
            - '@cisco.activity.activity_manager'
        scope: request
