services:
    wg.activity.milestone.form:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - wg_activity_milestone
            - '@wg.activity.milestone.form.type'
    wg.activity.milestone.form.type:
        class:  WG\ActivityBundle\Form\Type\MilestoneFormType
        arguments:
            - WG\ActivityBundle\Entity\Milestone
    wg.activity.milestone.form.handler:
        class: WG\ActivityBundle\Form\FormHandler
        arguments:
            - '@wg.activity.milestone.form'
            - '@request'
            - '@wg.activity.milestone_manager'
        scope: request
