services:
    cisco.activity.milestone.form:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - cisco_activity_milestone
            - '@cisco.activity.milestone.form.type'
    cisco.activity.milestone.form.type:
        class:  CiscoSystems\ActivityBundle\Form\Type\MilestoneFormType
        arguments:
            - CiscoSystems\ActivityBundle\Entity\Milestone
    cisco.activity.milestone.form.handler:
        class: CiscoSystems\ActivityBundle\Form\FormHandler
        arguments:
            - '@cisco.activity.milestone.form'
            - '@request'
            - '@cisco.activity.milestone_manager'
        scope: request
