services:
    cisco.activity.project.form:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - cisco_activity_project
            - '@cisco.activity.project.form.type'
    cisco.activity.project.form.type:
        class:  CiscoSystems\ActivityBundle\Form\Type\ProjectFormType
        arguments:
            - CiscoSystems\ActivityBundle\Entity\Project
    cisco.activity.project.form.handler:
        class: CiscoSystems\ActivityBundle\Form\FormHandler
        arguments:
            - '@cisco.activity.project.form'
            - '@request'
            - '@cisco.activity.project_manager'
        scope: request
