services:
    cisco.activity.context.context_factory:
        class: CiscoSystems\ActivityBundle\DependencyInjection\Factory\ContextFactory
        arguments:
            - '@security.context'
    cisco.activity.context.user:
        class: CiscoSystems\ActivityBundle\Model\UserInterface
        factory_service: cisco.activity.context.context_factory
        factory_method: getUser
    cisco.activity.business_time:
        class: CiscoSystems\ActivityBundle\Time\BusinessTime
        arguments:
            - '@doctrine.orm.entity_manager'
    cisco.twig.activity_extension:
        class: CiscoSystems\ActivityBundle\Twig\Extension\ActivityExtension
        arguments:
            - '@cisco.activity.business_time'
            - '@cisco.activity.context.user'
        tags:
            - { name: twig.extension }