parameters:
    cisco.activity.instance_manager.class:  CiscoSystems\ActivityBundle\Model\InstanceManager

services:
    cisco.activity.project_manager:
        class:  %cisco.activity.instance_manager.class%
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - CiscoSystems\ActivityBundle\Document\Project
    cisco.activity.milestone_manager:
        class:  %cisco.activity.instance_manager.class%
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - CiscoSystems\ActivityBundle\Document\Milestone
    cisco.activity.activity_manager:
        class:  %cisco.activity.instance_manager.class%
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - CiscoSystems\ActivityBundle\Document\Activity