parameters:
    cisco.activity.project_manager.class:  CiscoSystems\ActivityBundle\Model\ProjectManager
    cisco.activity.milestone_manager.class:  CiscoSystems\ActivityBundle\Model\MilestoneManager
    cisco.activity.activity_manager.class:  CiscoSystems\ActivityBundle\Model\ActivityManager
    cisco.activity.workweek_manager.class:  CiscoSystems\ActivityBundle\Model\WorkWeekManager
    cisco.activity.workunit_manager.class:  CiscoSystems\ActivityBundle\Model\WorkUnitManager

services:
    cisco.activity.project_manager:
        class:  %cisco.activity.project_manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - CiscoSystems\ActivityBundle\Entity\Project
    cisco.activity.milestone_manager:
        class:  %cisco.activity.milestone_manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - CiscoSystems\ActivityBundle\Entity\Milestone
    cisco.activity.activity_manager:
        class:  %cisco.activity.activity_manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - CiscoSystems\ActivityBundle\Entity\Activity
    cisco.activity.workweek_manager:
        class:  %cisco.activity.workweek_manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - CiscoSystems\ActivityBundle\Entity\WorkWeek
    cisco.activity.workunit_manager:
        class:  %cisco.activity.workunit_manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - CiscoSystems\ActivityBundle\Entity\WorkUnit