cisco_activity_dashboard:
    pattern:  /
    defaults: { _controller: CiscoSystemsActivityBundle:Dashboard:index }

############
# Projects #
############

cisco_activity_projects:
    pattern:  /projects
    defaults: { _controller: CiscoSystemsActivityBundle:Project:list }

cisco_activity_projects_new:
    pattern:  /projects/new
    defaults: { _controller: CiscoSystemsActivityBundle:Project:new }

cisco_activity_projects_show:
    pattern:  /projects/{id}
    defaults: { _controller: CiscoSystemsActivityBundle:Project:show }

cisco_activity_projects_edit:
    pattern:  /projects/{id}/edit
    defaults: { _controller: CiscoSystemsActivityBundle:Project:edit }

cisco_activity_projects_delete:
    pattern:  /projects/{id}/delete
    defaults: { _controller: CiscoSystemsActivityBundle:Project:delete }

##############
# Milestones #
##############

cisco_activity_milestones:
    pattern:  /milestones
    defaults: { _controller: CiscoSystemsActivityBundle:Milestone:list }

cisco_activity_milestones_new:
    pattern:  /milestones/new
    defaults: { _controller: CiscoSystemsActivityBundle:Milestone:new }

cisco_activity_milestones_show:
    pattern:  /milestones/{id}
    defaults: { _controller: CiscoSystemsActivityBundle:Milestone:show }

cisco_activity_milestones_edit:
    pattern:  /milestones/{id}/edit
    defaults: { _controller: CiscoSystemsActivityBundle:Milestone:edit }

cisco_activity_milestones_delete:
    pattern:  /milestones/{id}/delete
    defaults: { _controller: CiscoSystemsActivityBundle:Milestone:delete }

###########
# Roadmap #
###########

cisco_activity_roadmap:
    pattern:  /roadmap
    defaults: { _controller: CiscoSystemsActivityBundle:Roadmap:index }
